import type { NextPage } from "next";
import Head from "next/head";
import type { GetStaticProps } from "next";
import type { ParsedUrlQuery } from "querystring";

import MainApp from "../src/MainApp";
import data from "../public/data.json";
import PostsPage from "../src/post/pages/PostsPage";
// interface QParams extends ParsedUrlQuery {
//   slug?: string;
// }


const posts = data.filter(
  (item) => item.sys.contentType.sys.id === "post"
);
const definedPages = posts.map((post) => post.fields.slug?.["en-US"]);

const Home: NextPage = () => {
  // console.log("Posts: ", posts)
  // console.log("Defined pages: ", definedPages);
  return (
    <div>
      <Head>
        <title>Blog application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostsPage />

      {/* <main >
        <h1>Main application</h1>
      </main>

      <footer >
        
          Powered by{' '}
      </footer> */}
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async (props) => {
  // const {locale} = props;
  // const { slug } = params;
  // console.log({ slug });
  console.log("index props: ", props);

  return {
    props: {
      pages: definedPages,
      ...props,
    },
  };
};
