import { useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

import { getCategories, getPosts } from "@post/helpers";
import PostsPage from "../src/post/pages/PostsPage";

import type { ReactElement } from "react";
import type { NextRouter } from "next/router";
import type { GetStaticProps, InferGetStaticPropsType } from "next";
import type { Category, CategoryFields, PostFields } from "@typings/contentful";

const Home = ({
  categories,
  posts: postsProps,
}: InferGetStaticPropsType<typeof getStaticProps>): ReactElement => {
  const router: NextRouter = useRouter();
  const [posts, setPosts] = useState<PostFields[]>(postsProps);

  useEffect(() => {
    router.replace("/", undefined, { shallow: false });
  }, []);

  useEffect(() => {
    const onRouteChange = (url: string): void => {
      let category: string[] | string = url.split("?");

      if (category.length === 1) {
        setPosts(postsProps);
        return;
      }
      category = category[1].split("=");
      category = category[1];

      const filtered: PostFields[] = postsProps.filter((post: PostFields) => {
        const postCategories: Category[] | undefined = post.categories;
        const postHasCategory: number | undefined = postCategories?.findIndex(
          (postCategory: Category) => postCategory.fields.slug === category
        );
        if (postHasCategory !== -1) return post;
      });

      setPosts(filtered);
    };

    router.events.on("routeChangeComplete", onRouteChange);
  }, [router.events]);

  return (
    <div>
      <Head>
        <title>Blog application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/gluo.ico" />
      </Head>
      <PostsPage posts={posts} categories={categories} />
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<{
  categories: CategoryFields[];
  posts: PostFields[];
}> = async (props) => {
  const posts: PostFields[] = getPosts();
  const categories: CategoryFields[] = getCategories();

  return {
    props: {
      categories,
      posts,
      ...props,
    },
  };
};
